<?php

namespace App\Http\Controllers;

use App\Enums\QuotaType;
use App\Exceptions\QuotaExceededException;
use App\Models\Application;
use App\Services\Ai\AiService;
use App\Services\AppLogger;
use App\Services\QuotaService;
use Illuminate\Support\HtmlString;

class AiController extends Controller
{
    private const AI_DISCLAIMER = '<p class="mt-4 text-xs italic text-gray-500 dark:text-gray-500">This response was generated by AI and should be reviewed for accuracy before use.</p>';

    private const QUOTA_EXCEEDED_MESSAGE = '<div class="p-4 bg-red-50 dark:bg-red-900/20 rounded-lg"><p class="text-sm text-red-600 dark:text-red-400"><strong>AI Quota Exceeded:</strong> The daily AI usage limit has been reached. Please try again tomorrow or contact your administrator.</p></div>';

    /**
     * Get AI-generated control checking response.
     */
    public static function getImplementationCheck($record): HtmlString
    {
        // Check quota before making API call
        try {
            QuotaService::check(QuotaType::AI_PROMPT);
            QuotaService::check(QuotaType::AI_RESPONSE);
        } catch (QuotaExceededException $e) {
            AppLogger::warning(
                'ai',
                'QuotaExceeded',
                'AI implementation check blocked due to quota',
                [
                    'control_id' => $record->id,
                    'quota_type' => $e->getQuotaType()->value,
                    'usage' => $e->getCurrentUsage(),
                    'limit' => $e->getLimit(),
                ],
                $record
            );

            return new HtmlString(self::QUOTA_EXCEEDED_MESSAGE);
        }

        $systemPrompt = <<<'PROMPT'
        You are an experienced information security professional specializing in control implementation and compliance frameworks (SOC 2, ISO 27001, NIST, COSO, etc.).

        Your task is to determine if the implementations provided meet the requirements of the specified security control.

        Response requirements:
        - Respond with a single "Meets Requirements", "Does Not Meet Requirements", or "Partially Meets Requirements"
        - Include a justification for you response in exactly one paragraph (3-5 sentences)
        - Use plain language suitable for both technical and non-technical stakeholders
        - Reference specific tools, processes, or documentation where appropriate
        - Respond in html format with the following structure:
            <div class="space-y-4">
                <div>
                    <h4 class="text-sm font-semibold text-gray-900 dark:text-gray-100">Conclusion</h4>
                    <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">[Your conclusion here]</p>
                </div>
                <div>
                    <h4 class="text-sm font-semibold text-gray-900 dark:text-gray-100">Justification</h4>
                    <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">[Your justification here]</p>
                </div>
                <div>
                    <h4 class="text-sm font-semibold text-gray-900 dark:text-gray-100">Recommendations</h4>
                    <ul class="mt-1 text-sm text-gray-600 dark:text-gray-400 list-disc list-inside space-y-1">
                        <li>[Recommendation 1]</li>
                        <li>[Recommendation 2]</li>
                    </ul>
                </div>
            </div>
        - For any lists, use: <ul class="mt-1 text-sm text-gray-600 dark:text-gray-400 list-disc list-inside space-y-1"> with <li> items
        PROMPT;

        $implementations = $record->implementations()->pluck('details')->join("\n") ?: 'None';
        $applicationNames = Application::get()->pluck('name')->toArray();
        $applications = !empty($applicationNames) ? json_encode($applicationNames) : 'None';

        $description = $record['description'] ?: 'None';
        $discussion = $record['discussion'] ?: 'None';
        $testProcedures = $record['test_procedures'] ?: 'None';

        $userPrompt = "User has the following implementations currently: {$implementations}.
            User also has the following applications currently: {$applications}.
            Evaluate the implementations against the following security control: {$description}
            Security Control Discussion: {$discussion}
            Security Control Test Procedures: {$testProcedures}
            ";

        $aiService = new AiService;
        $response = $aiService->chatCompletion($systemPrompt, $userPrompt);

        // Record quota usage after successful API call
        if (isset($response['usage']['prompt_tokens'])) {
            QuotaService::record(QuotaType::AI_PROMPT, $response['usage']['prompt_tokens']);
        }
        if (isset($response['usage']['completion_tokens'])) {
            QuotaService::record(QuotaType::AI_RESPONSE, $response['usage']['completion_tokens']);
        }

        AppLogger::info(
            'ai',
            'ImplementationCheck',
            'AI implementation check completed',
            [
                'control_id' => $record->id,
                'provider' => $aiService->getProvider()->value,
                'model' => $response['model'],
                'prompt_tokens' => $response['usage']['prompt_tokens'] ?? null,
                'completion_tokens' => $response['usage']['completion_tokens'] ?? null,
                'total_tokens' => $response['usage']['total_tokens'] ?? null,
            ],
            $record
        );

        return new HtmlString($response['content'].self::AI_DISCLAIMER);
    }

    /**
     * Get AI-generated implementation suggestions for a security control.
     */
    public static function getControlSuggestions($record): HtmlString
    {
        // Check quota before making API call
        try {
            QuotaService::check(QuotaType::AI_PROMPT);
            QuotaService::check(QuotaType::AI_RESPONSE);
        } catch (QuotaExceededException $e) {
            AppLogger::warning(
                'ai',
                'QuotaExceeded',
                'AI control suggestions blocked due to quota',
                [
                    'control_id' => $record->id,
                    'quota_type' => $e->getQuotaType()->value,
                    'usage' => $e->getCurrentUsage(),
                    'limit' => $e->getLimit(),
                ],
                $record
            );

            return new HtmlString(self::QUOTA_EXCEEDED_MESSAGE);
        }

        $systemPrompt = <<<'PROMPT'
        You are an experienced information security professional specializing in control implementation and compliance frameworks (SOC 2, ISO 27001, NIST, COSO, etc.).

        Your task is to provide practical, actionable implementation guidance for security controls.

        Response requirements:
        - Write exactly one paragraph (3-5 sentences)
        - Focus on concrete, implementable steps
        - Use plain language suitable for both technical and non-technical stakeholders
        - Reference specific tools, processes, or documentation where appropriate
        - Do not include headers, bullet points, or markdown formatting
        PROMPT;

        $applicationNames = Application::get()->pluck('name')->toArray();
        $applications = !empty($applicationNames) ? json_encode($applicationNames) : 'None';

        $description = $record['description'] ?: 'None';
        $discussion = $record['discussion'] ?: 'None';
        $testProcedures = $record['test_procedures'] ?: 'None';

        $userPrompt = "User has the following applications currently: {$applications}.
            Provide a sample implementation description for
            the following security control: {$description}
            Control Discussion: {$discussion}
            Control Test Procedures: {$testProcedures}
            ";

        $aiService = new AiService;
        $response = $aiService->chatCompletion($systemPrompt, $userPrompt);

        // Record quota usage after successful API call
        if (isset($response['usage']['prompt_tokens'])) {
            QuotaService::record(QuotaType::AI_PROMPT, $response['usage']['prompt_tokens']);
        }
        if (isset($response['usage']['completion_tokens'])) {
            QuotaService::record(QuotaType::AI_RESPONSE, $response['usage']['completion_tokens']);
        }

        return new HtmlString($response['content'].self::AI_DISCLAIMER);
    }
}
